<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
        <UserSecretsId>c165956c-842d-478c-97ce-5fba60daff00</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../Shared/Shared.csproj"/>
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
