-- ============================================================
-- Identity test account seed
-- ============================================================
-- 7 accounts:
--   1 ADMIN
--   1 MANAGER
--   1 ASSISTANT
--   2 EMPLOYEE
--   2 CUSTOMER
--
-- IMPORTANT:
-- account_password is intentionally generated by C# using the
-- real IPasswordHasher/AccountHelper implementation, because the
-- hash depends on your application's hashing implementation.
--
-- Replace <HASH_...> after running the C# generator.
-- ============================================================
START TRANSACTION;
INSERT INTO `account`
(`account_id`,
 `account_email`,
 `account_password`,
 `account_created_at`,
 `account_updated_at`,
 `account_is_active`,
 `account_phone_number`)
VALUES (UUID_V7(), 'admin@test.local', 'Thienlang01!', NOW(), NOW(), TRUE, '0900000001'),
       (UUID_V7(), 'manager@test.local', 'Thienlang01!', NOW(), NOW(), TRUE, '0900000002'),
       (UUID_V7(), 'assistant@test.local', 'Thienlang01!', NOW(), NOW(), TRUE, '0900000003'),
       (UUID_V7(), 'employee01@test.local', 'Thienlang01!', NOW(), NOW(), TRUE, '0900000004'),
       (UUID_V7(), 'employee02@test.local', 'Thienlang01!', NOW(), NOW(), TRUE, '0900000005'),
       (UUID_V7(), 'customer01@test.local', 'Thienlang01!', NOW(), NOW(), TRUE, '0900000006'),
       (UUID_V7(), 'customer02@test.local', 'Thienlang01!', NOW(), NOW(), TRUE, '0900000007');

-- ============================================================
-- Assign roles by stable role_code, not generated UUIDs.
-- ============================================================

INSERT INTO `account_role` (`account_id`, `role_id`, `assigned_at`)
SELECT a.`account_id`, r.`role_id`, NOW()
FROM `account` a
         JOIN `role` r ON r.`role_code` = 'ADMIN'
WHERE a.`account_email` = 'admin@test.local';

INSERT INTO `account_role` (`account_id`, `role_id`, `assigned_at`)
SELECT a.`account_id`, r.`role_id`, NOW()
FROM `account` a
         JOIN `role` r ON r.`role_code` = 'MANAGER'
WHERE a.`account_email` = 'manager@test.local';

INSERT INTO `account_role` (`account_id`, `role_id`, `assigned_at`)
SELECT a.`account_id`, r.`role_id`, NOW()
FROM `account` a
         JOIN `role` r ON r.`role_code` = 'ASSISTANT'
WHERE a.`account_email` = 'assistant@test.local';

INSERT INTO `account_role` (`account_id`, `role_id`, `assigned_at`)
SELECT a.`account_id`, r.`role_id`, NOW()
FROM `account` a
         JOIN `role` r ON r.`role_code` = 'EMPLOYEE'
WHERE a.`account_email` IN ('employee01@test.local', 'employee02@test.local');

INSERT INTO `account_role` (`account_id`, `role_id`, `assigned_at`)
SELECT a.`account_id`, r.`role_id`, NOW()
FROM `account` a
         JOIN `role` r ON r.`role_code` = 'CUSTOMER'
WHERE a.`account_email` IN ('customer01@test.local', 'customer02@test.local');

-- ============================================================
-- Two additional permissions for testing account-level overrides.
-- ============================================================

INSERT INTO `account_additional_permission`
    (`account_id`, `permission_id`, `assigned_at`)
SELECT a.`account_id`, p.`permission_id`, NOW()
FROM `account` a
         JOIN `permission` p ON p.`permission_code` = 'StatisticsRead'
WHERE a.`account_email` = 'employee01@test.local';

INSERT INTO `account_additional_permission`
    (`account_id`, `permission_id`, `assigned_at`)
SELECT a.`account_id`, p.`permission_id`, NOW()
FROM `account` a
         JOIN `permission` p ON p.`permission_code` = 'ProductSell'
WHERE a.`account_email` = 'customer01@test.local';

COMMIT;

select *
from `account`;
select *
from user_profile;
select *
from `account_role`;
select *
from `role`;
select *
from `permission`;
select *
from `role_permission`;
select *
from `account_additional_permission`;


select *
from account_role
where account_role.account_id = '01a052fc-efb9-7ef1-b57f-029e779396de';
select *
from account
where account.account_phone_number LIKE '084%';